export JAVA_HOME=/usr/local/jdk1.7.0_80/ 
export PATH=$PATH:$JAVA_HOME/bin
export SPARK_INSTALL=/usr/local/spark
export SPARK_HOME=$SPARK_INSTALL 
export PATH=$PATH:$SPARK_INSTALL/bin  
export PATH=$PATH:$SPARK_INSTALL/sbin  
